on:
  workflow_call:
    inputs:
      platform_env:
        required: true
        type: string
      platform_name:
        required: true
        type: string
      artifact_path:
        required: true
        type: string


jobs:
  build:
    name: Building ${{ inputs.platform_name }} release
    runs-on: ${{ inputs.platform_env }}
    steps:
      - name: Checkout master version
        uses: actions/checkout@master
      - name: Generate the artifacts
        run: |
          cargo build --release
      # [2025-09-19T23:06:43+08:00] this job cannot upload multiple artifacts to
      # the same release. Temporarily replace this job with offical
      # upload-artifact job for stashing but release in manual way
      #
      # - name: upload binary to github release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: "target/release/ffmpeg_ext"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload binary to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg_ext-${{ inputs.platform_name }}-${{ github.ref_name }}
          path: ${{ inputs.artifact_path }}
permissions:
  contents: write
