on:
  push:
    tags:
      - "v*.*.*"

name: Release Event
jobs:
  release-ubuntu:
    uses: ./.github/workflows/commons_release.yml
    with:
      platform: ubuntu-latest
  release-windows:
    uses: ./.github/workflows/commons_release.yml
    with:
      platform: windows-latest
  release-macos:
    uses: ./.github/workflows/commons_release.yml
    with:
      platform: macos-latest
